- Title: Anti-Reverse Engineering
  Content: TrulyProtect's patented solution is the only product in the market
          which employs pure encryption while protecting your most precious
          intellectual property. Using our patented solutions you can protect
          your application from IP theft, verift the app authentication and have
          it run as intended.

- Title: Realtime Data Protection
  Content: TrulyProtect's SecureData ensures your applications data is safe and
           secure, our product can seperate your applications memory buffers
           from the rest of the computer thus promising all unauthorised 3rd
           party applications cannot access it and steal your information.

- Title: Application "Firewall"
  Content: Borrowing from the firewall concept, our Application Firewall
           prohibits the execution of any unauthorised piece of code thus it
           guards your production servers, endpoints and critical machines
           even from the possibility of the executing any malicous software.
